
from config import *
def init_ui(self):
        self.setWindowTitle('Cookie Tester v 2.0')
        self.resize(700, 450)
        # Center the GUI on the screen
        screen_geometry = QApplication.desktop().screenGeometry()
        x = (screen_geometry.width() - self.width()) // 2
        y = (screen_geometry.height() - self.height()) // 2
        self.move(x, y)
        layout = QVBoxLayout()
        self.result_layout = QHBoxLayout()
        self.result_label = QLabel('')
        self.result_layout.addWidget(self.result_label)
        self.result_layout.addStretch(1)
        self.import_button = QPushButton('IMPORT COOKIES', self)
        self.import_button.clicked.connect(self.import_cookies)
        self.import_button.setStyleSheet(ButtonStyleSheet)
        layout.addWidget(self.import_button)
        self.test_button = QPushButton('CHECK ALL COOKIES', self)
        self.test_button.clicked.connect(self.test_all_cookies)
        self.test_button.setStyleSheet(ButtonStyleSheet_GRAY)
        layout.addWidget(self.test_button)
        self.import_button = QPushButton('COOKIES STRING', self)
        self.import_button.clicked.connect(self.COOKIE_WINDOW_TOPAST)
        self.import_button.setStyleSheet(ButtonStyleSheet)
        layout.addWidget(self.import_button)
        self.result_label2 = QLabel('')
        self.result_label2.setAlignment(Qt.AlignCenter)
        self.result_label2.setFont(QFont("calibri", 11, QFont.Bold))
        self.result_label2.setVisible(False)
        layout.addWidget(self.result_label2)
        self.cookies_listbox = QComboBox(self)
        self.cookies_listbox.setPlaceholderText("Select file...")
        self.cookies_listbox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self.cookies_listbox.setEditable(True)
        self.cookies_listbox.lineEdit().setAlignment(Qt.AlignCenter)
        self.cookies_listbox.lineEdit().setReadOnly(True)
        self.cookies_listbox.lineEdit().setPlaceholderText("Select file...")
        self.cookies_listbox.setStyleSheet(ComboBoxStyleSheet)
        layout.addWidget(self.cookies_listbox)
        self.current_label = QLabel('')
        self.current_label.setAlignment(Qt.AlignCenter)
        self.current_label.setFont(QFont("calibri", 11, QFont.Bold))
        self.current_label.setVisible(False)
        layout.addWidget(self.current_label)
        self.progress_bar_main = QProgressBar(self)
        self.progress_bar_main.setStyleSheet(progressbarStyleSheets)
        layout.addWidget(self.progress_bar_main)
        self.progress_bar_main.hide()
        self.result_label = QLabel('')
        self.result_label.setAlignment(Qt.AlignCenter)
        self.result_label.setFont(QFont("calibri", 13, QFont.Bold))
        layout.addWidget(self.result_label)
        self.account_details_table = QTableWidget()
        self.account_details_table.setColumnCount(5)
        self.account_details_table.setHorizontalHeaderLabels(['Email', 'Subscription Plan', 'Membership', 'Profils', 'file'])
        self.account_details_table.setEditTriggers(QTableWidget.NoEditTriggers)
        self.account_details_table.cellClicked.connect(self.open_text_file)
        self.account_details_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.account_details_table.setStyleSheet(WidgetTableStyleSheet)
        last_column = self.account_details_table.columnCount() - 1
        self.account_details_table.horizontalHeader().setSectionResizeMode(last_column, QHeaderView.Stretch)
        layout.addWidget(self.account_details_table)
        layout.setSpacing(6)  # Set spacing between widgets
        # Set the background gradient
        gradient = QLinearGradient(0, 0, 0, self.height())
        gradient.setColorAt(0, QColor(240, 240, 240))
        gradient.setColorAt(1, QColor(220, 220, 220))
        palette = QPalette()
        palette.setBrush(QPalette.Window, QBrush(gradient))
        self.setPalette(palette)
        layout.addWidget(self.test_button)
        self.close_button = QPushButton('COOKIES STRING', self)
        self.close_button.clicked.connect(self.closeEvent)
        self.close_button.setStyleSheet(ButtonStyleSheet)
        #-----------------------------------------------
        self.setLayout(layout)
